#############################################################################
# will_filter configuration
#
# Default settings for all environments
# 
# You can overload any feature for any environment by changing the 
# environment settings at the bottom of the file. 
#
# Alternatively, you can overload any of the methods of Wf::Config
#############################################################################

defaults: &defaults
  effects_options:
    enabled:              false
    script_path:          "/wf/javascripts/will_filter_prototype_effects.js"
    
  save_options: 
    enabled:              true
    user_filters_enabled: false   # if set to true, the filters will be private
    user_class_name:      User 
    current_user_method:  current_user 

  export_options:         
    enabled:              true
    default_formats:      [table, csv, xml, json]
  
  containers:             # container implementation mapping
    nil:                  Wf::Containers::Nil
    numeric:              Wf::Containers::Numeric
    numeric_range:        Wf::Containers::NumericRange
    numeric_delimited:    Wf::Containers::NumericDelimited
    date_time_range:      Wf::Containers::DateTimeRange
    single_date:          Wf::Containers::SingleDate
    date:                 Wf::Containers::Date
    date_time:            Wf::Containers::DateTime
    date_range:           Wf::Containers::DateRange
    text:                 Wf::Containers::Text
    text_delimited:       Wf::Containers::TextDelimited
    boolean:              Wf::Containers::Boolean
    list:                 Wf::Containers::List
    filter_list:          Wf::Containers::FilterList
    
  data_types:             # mapping between data types and containers   
    bigint:               [nil, numeric, numeric_range, numeric_delimited]
    numeric:              [nil, numeric, numeric_range, numeric_delimited]
    smallint:             [nil, numeric, numeric_range, numeric_delimited]
    integer:              [nil, numeric, numeric_range, numeric_delimited]
    int:                  [nil, numeric, numeric_range, numeric_delimited]
    double:               [nil, numeric, numeric_range, numeric_delimited]
    timestamp:            [nil, date_time, date_time_range, single_date]
    datetime:             [nil, date_time, date_time_range, single_date]
    date:                 [nil, date, date_range]
    character:            [nil, text, text_delimited]
    varchar:              [nil, text, text_delimited]
    text:                 [nil, text, text_delimited]
    text[]:               [nil, text, text_delimited]
    bytea:                [nil, text, text_delimited]
    boolean:              [nil, boolean]
    tinyint:              [nil, boolean]

  operators:              # operators precedence
    is:                   100
    is_not:               200
    is_on:                300
    is_in:                400
    is_provided:          500
    is_not_provided:      600 
    is_after:             700
    is_before:            800
    is_in_the_range:      900
    contains:             1000
    does_not_contain:     1100
    starts_with:          1200
    ends_with:            1300
    is_greater_than:      1400
    is_less_than:         1500
    is_filtered_by:       1600
    
    
#############################################################################
# Environment Settings
# You can overload any feature defined in the defaults for any environment
#############################################################################
development:
  <<: *defaults
  
test:
  <<: *defaults
      
qa:
  <<: *defaults

stage:
  <<: *defaults

production:
  <<: *defaults
