#############################################################################
#
# Tr8n Default Value Rules
#
# Definition:
#   operator:     is, is_not
#   value1:       male, female, unknown
#
#############################################################################

en-US:
ru:
  rule1:
    operator:   starts_with 
    value:      "а, и, о, у, ы, э, А, И, О, У, Э"
  rule2:
    operator:   does_not_start_with 
    value:      "а, и, о, у, ы, э, А, И, О, У, Э"
