#############################################################################
#
# Tr8n Default Language Cases
#
#############################################################################

en-US:
  case1:
    keyword:          "nom"
    latin_name:       "Nominative"
    native_name:      "Nominative" 
    description:      "Used for any noun or pronoun that is the  subject of a verb"
  case2:
    keyword:          "obj"
    latin_name:       "Objective"
    native_name:      "Objective" 
    description:      "Used in the direct object, indirect object, object of preposition, object complement, and subject of an infinitive"
  case3:
    keyword:          "pos"
    latin_name:       "Possessive"
    native_name:      "Possessive" 
    description:      "Used to indicate possession (i.e., ownership). It is usually created by adding 's to the word"
    rules:
      rule1:
        multipart:    false 
        gender:       none
        part1:        ends_in
        value1:       "s"
        operation:    append
        value:        "'"
      rule2:
        multipart:    false 
        gender:       none
        part1:        does_not_end_in
        value1:       "s"
        operation:    append
        value:        "'s"
  case4:
    keyword:          "ord"
    latin_name:       "Ordinal"
    native_name:      "Ordinal" 
    description:      "The adjective form of the cardinal numbers"
    rules:            
      rule1:
        multipart:    true 
        gender:       none
        part1:        ends_in
        value1:       "1"
        operator:     and
        part2:        does_not_end_in
        value2:       "11"
        operation:    append
        value:        "st"
      rule2:
        multipart:    true 
        gender:       none
        part1:        ends_in
        value1:       "2"
        operator:     and
        part2:        does_not_end_in
        value2:       "12"
        operation:    append
        value:        "nd"
      rule3:
        multipart:    true 
        gender:       none
        part1:        ends_in
        value1:       "3"
        operator:     and
        part2:        does_not_end_in
        value2:       "13"
        operation:    append
        value:        "rd"
      rule4:
        multipart:    false 
        gender:       none
        part1:        ends_in
        value1:       "0,4,5,6,7,8,9,11,12,13"
        operation:    append
        value:        "th"
      
ru:
  case1:                
    keyword:          "nom"
    latin_name:       "Nominativus"
    native_name:      "Именительный падеж" 
    description:      "Есть - Кто? Что?"
  case2:               
    keyword:          "gen"
    latin_name:       "Genitivus"
    native_name:      "Родительный падеж" 
    description:      "Нет - Кого? Чего?"
    rules:            
      rule1:
        multipart:    false 
        gender:       male
        part1:        ends_in
        value1:       "б, в, г, д, ж, з, к, л, м, н, п, р, с, т, ф, х, ц, ч, ш, щ"
        operation:    append
        value:        "a"
      rule2:
        multipart:    false 
        gender:       male
        part1:        ends_in
        value1:       "й"
        operation:    replace
        value:        "я"
      rule3:
        multipart:    false 
        gender:       female
        part1:        ends_in
        value1:       "а"
        operation:    replace
        value:        "ы"
      rule3:
        multipart:    false 
        gender:       female
        part1:        ends_in
        value1:       "я"
        operation:    replace
        value:        "и"
  case3:               
    keyword:          "dat"
    latin_name:       "Dativus"
    native_name:      "Дательный падеж" 
    description:      "Рад - Кому? Чему?"
  case4:               
    keyword:          "acc"
    latin_name:       "Accusativus"
    native_name:      "Винительный падеж" 
    description:      "Вижу - Кого? Что?"
  case5:               
    keyword:          "ins"
    latin_name:       "Instrumentalis"
    native_name:      "Творительный падеж" 
    description:      "Доволен - Кем? Чем?"
  case6:               
    keyword:          "pre"
    latin_name:       "Prepositivus"
    native_name:      "Предложный падеж" 
    description:      "Думаю - О ком? О чём?"
