#############################################################################
#
# Tr8n Default Gender List Rules
#
# Definition:
#   multipart:    true, false
#   part1:        contains
#   value1:       one_element, at_least_two_elements
#   part2:        is, is_not, are, are_not
#   value2:       male, female, unknown, all_male, all_female, mixed
# 
#############################################################################

en-US:
  rule1: 
    multipart:    false
    part1:        contains
    value1:       one_element
  rule2: 
    multipart:    false
    part1:        contains
    value1:       at_least_two_elements
iw: 
  rule1: 
    multipart:    true
    part1:        contains
    value1:       one_element
    part2:        is
    value2:       male
  rule2: 
    multipart:    true
    part1:        contains
    value1:       one_element
    part2:        is
    value2:       female
  rule3: 
    multipart:    true
    part1:        contains
    value1:       one_element
    part2:        is
    value2:       unknown
  rule4: 
    multipart:    true
    part1:        contains
    value1:       at_least_two_elements
    part2:        are
    value2:       all_male
  rule5: 
    multipart:    true
    part1:        contains
    value1:       at_least_two_elements
    part2:        are
    value2:       all_female
  rule6: 
    multipart:    true
    part1:        contains
    value1:       at_least_two_elements
    part2:        are
    value2:       mixed
ru: 
  rule1: 
    multipart:    true
    part1:        contains
    value1:       one_element
    part2:        is
    value2:       male
  rule2: 
    multipart:    true
    part1:        contains
    value1:       one_element
    part2:        is
    value2:       female
  rule3: 
    multipart:    true
    part1:        contains
    value1:       one_element
    part2:        is
    value2:       unknown
  rule4: 
    multipart:    false
    part1:        contains
    value1:       at_least_two_elements
