#############################################################################
#
# Tr8n Sample Glossary
#
#############################################################################

Poster:       "A poster is any piece of printed paper designed to be attached to a wall or vertical surface. Typically posters include both textual and graphic elements, although a poster may be either wholly graphical or wholly text."
Tree:         "A family tree, or pedigree chart, is a chart representing family relationships in a conventional tree structure. The more detailed family trees used in medicine, genealogy, and social work are known as genograms."
Print:        "Printing is a process for reproducing text and image, typically with ink on paper using a printing press. It is often carried out as a large-scale industrial process, and is an essential part of publishing and transaction printing."
Profile:      "A user profile (userprofile, or simply profile when used in-context) is a collection of personal data associated to a specific user. A profile refers therefore to the explicit digital representation of a person's identity. A user profile can also be considered as the computer representation of a user model."
User:         "A person who uses computers for work or entertainment or communication or business."
Home:         "The homepage (often written as home page) is the URL or local file that automatically loads when a web browser starts or when the browser's \"home\" button is pressed. One can turn this feature off and on, as well as specify a URL for the page to be loaded."
Relatives:    "A person who is connected with another or others by blood or marriage."
Relative:     "A person who is connected with another or others by blood or marriage."
Photo:        "A picture produced by photography."
Inbox:        "An electronic folder for incoming e-mails or text messages."
Celebrities:  "A famous or well-known person. "
Privacy:      "The state of being free from unsanctioned intrusion: a person's right to privacy."
